#!/bin/bash

# Safely execute this bash script
# e exit on first failure
# x all executed commands are printed to the terminal
# u unset variables are errors
# a export all variables to the environment
# E any trap on ERR is inherited by shell functions
# -o pipefail | produces a failure code if any stage fails
set -Eeuoxa pipefail

# Get the directory of this script
LOCAL_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Build the container
$LOCAL_DIRECTORY/scripts/build.sh

docker run -it \
    -v ~/.backend:/root/.backend \
    -v $LOCAL_DIRECTORY/src:/app/mm-embedder-service/src \
    -v $LOCAL_DIRECTORY/backend:/app/mm-embedder-service/backend \
    -p 3000:5000 \
    -p 5001:5001 \
mm-embedder-service:latest

